In [3]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created :\n",a)

Array created :
 [[1 2 4]
 [5 8 7]]


In [4]:
import numpy as np
#creating a 3*4 array with all zeros
b=np.zeros((3,4))
print("array with all zeros :\n",b)

array with all zeros :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#create a constant value array
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [5]:
import numpy as np
#creating an array with random value
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.74508201 0.38334681]
 [0.44773155 0.24964485]]


In [11]:
#create a sequence of integers from 0 to 30 with step of 5 
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [23]:
#Reshaping 3*4 array to 2*2*2 array
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\n original array;\n",arr)
print("Reshaped array [4,3]:\n",newarr)


 original array;
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array [4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [29]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
print("\n No.of dimensions :\n",arr.ndim)
print("\n shape of array :\n",arr.shape)
print("\n size of array :\n",arr.size)
print("\n Array type :\n",arr.dtype)
newtype = arr.astype ('f')
print("\n converted array elements :\n",newtype)
print("\n converted array type :\n",newtype.dtype)
      


 No.of dimensions :
 2

 shape of array :
 (3, 4)

 size of array :
 12

 Array type :
 int32

 converted array elements :
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

 converted array type :
 float32


In [30]:
#slicing 
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:,3:])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]


In [32]:
#Flatten array
flarr=arr.flatten()
print("\n original array:\n",arr)
print("\n Flatten array:\n",flarr)


 original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Flatten array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [33]:
c= p.astype
print(c)
e=p.astype('i')
print(e)

<built-in method astype of numpy.ndarray object at 0x3674a20>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
